// Project detail data for individual project pages
// Each project has canvas items placed at absolute positions

export const PROJECT_DETAILS = {
  bento: {
    id: 'bento',
    title: 'Bento.fun',
    subtitle: 'Social layer for prediction markets',
    role: 'Brand Designer & Product Designer',
    year: '2024',
    tags: ['Rebrand', 'Visual Design', 'Product Design'],
    url: 'https://bento.fun',
    color: '#E8533F',
    canvasItems: [
      { type: 'hero', x: 200, y: 100, width: 700, image: '/work-bento.webp' },
      { type: 'heading', x: 200, y: 520, text: 'Bento.fun' },
      { type: 'text', x: 200, y: 580, width: 500, text: 'Bento.fun is a social layer for prediction market. Turn your group chat takes into markets — create, share and earn. Backed by Yzi Labs.' },
      { type: 'label', x: 200, y: 680, text: 'Role' },
      { type: 'text', x: 200, y: 710, width: 400, text: 'Brand Designer & Product Designer' },
      { type: 'label', x: 200, y: 770, text: 'Year' },
      { type: 'text', x: 200, y: 800, width: 200, text: '2024' },
      { type: 'label', x: 200, y: 860, text: 'Deliverables' },
      { type: 'text', x: 200, y: 890, width: 500, text: 'Complete rebrand including logo, color system, typography, iconography, marketing website, and product UI design.' },
      { type: 'section', x: 1000, y: 100, text: 'Screenshots' },
      { type: 'placeholder', x: 1000, y: 160, width: 500, height: 350, label: 'Homepage Design' },
      { type: 'placeholder', x: 1000, y: 560, width: 500, height: 350, label: 'Dashboard View' },
      { type: 'placeholder', x: 1550, y: 160, width: 500, height: 350, label: 'Mobile App' },
      { type: 'placeholder', x: 1550, y: 560, width: 500, height: 350, label: 'Brand Guidelines' },
      { type: 'sticky', x: 1550, y: 960, width: 250, text: 'Key challenge: Creating a brand that feels playful yet trustworthy for handling real money.', color: '#FEFF9C' },
    ],
  },
  'inner-circle': {
    id: 'inner-circle',
    title: 'Inner Circle',
    subtitle: 'Community of 10,000+ founders on Base',
    role: 'Website Designer & Visual Designer',
    year: '2024',
    tags: ['Website Design', 'Visual Design'],
    url: 'https://innercircle.so',
    color: '#7B2FBE',
    canvasItems: [
      { type: 'hero', x: 200, y: 100, width: 700, image: '/work-inner-circle.webp' },
      { type: 'heading', x: 200, y: 520, text: 'Inner Circle' },
      { type: 'text', x: 200, y: 580, width: 500, text: 'Inner Circle is a community of 10,000+ founders, creators, developers, designers on Base. Built a dynamic website that captures the energy of the community.' },
      { type: 'label', x: 200, y: 680, text: 'Role' },
      { type: 'text', x: 200, y: 710, width: 400, text: 'Website Designer & Visual Designer' },
      { type: 'label', x: 200, y: 770, text: 'Year' },
      { type: 'text', x: 200, y: 800, width: 200, text: '2024' },
      { type: 'label', x: 200, y: 860, text: 'Deliverables' },
      { type: 'text', x: 200, y: 890, width: 500, text: 'Landing page design, visual identity for web, community dashboard, and event pages.' },
      { type: 'section', x: 1000, y: 100, text: 'Screenshots' },
      { type: 'placeholder', x: 1000, y: 160, width: 500, height: 350, label: 'Landing Page' },
      { type: 'placeholder', x: 1000, y: 560, width: 500, height: 350, label: 'Community Hub' },
      { type: 'placeholder', x: 1550, y: 160, width: 500, height: 350, label: 'Events Page' },
      { type: 'sticky', x: 1550, y: 560, width: 250, text: 'The purple gradient became the signature visual element — it represents the "inner" feeling of belonging.', color: '#D5B8FF' },
    ],
  },
  velar: {
    id: 'velar',
    title: 'Velar',
    subtitle: 'DeFi liquidity protocol on Bitcoin',
    role: 'Website Designer & Product Designer',
    year: '2024',
    tags: ['Website Design', 'Product Design'],
    url: 'https://velar.co',
    color: '#E8533F',
    canvasItems: [
      { type: 'hero', x: 200, y: 100, width: 700, image: '/work-velar.webp' },
      { type: 'heading', x: 200, y: 520, text: 'Velar' },
      { type: 'text', x: 200, y: 580, width: 500, text: 'Velar is a DeFi liquidity protocol built on Bitcoin. Trade, provide liquidity, and earn rewards on Bitcoin\'s secure network.' },
      { type: 'label', x: 200, y: 680, text: 'Role' },
      { type: 'text', x: 200, y: 710, width: 400, text: 'Website Designer & Product Designer' },
      { type: 'label', x: 200, y: 770, text: 'Year' },
      { type: 'text', x: 200, y: 800, width: 200, text: '2024' },
      { type: 'label', x: 200, y: 860, text: 'Deliverables' },
      { type: 'text', x: 200, y: 890, width: 500, text: 'Marketing website redesign, swap interface, liquidity pool dashboards, and token analytics pages.' },
      { type: 'section', x: 1000, y: 100, text: 'Screenshots' },
      { type: 'placeholder', x: 1000, y: 160, width: 500, height: 350, label: 'Marketing Site' },
      { type: 'placeholder', x: 1000, y: 560, width: 500, height: 350, label: 'Swap Interface' },
      { type: 'placeholder', x: 1550, y: 160, width: 500, height: 350, label: 'Analytics Dashboard' },
      { type: 'sticky', x: 1550, y: 560, width: 250, text: 'Challenge: Making complex DeFi concepts feel simple and approachable for everyday users.', color: '#FFD59E' },
    ],
  },
  emerge: {
    id: 'emerge',
    title: 'Emerge',
    subtitle: 'Visual storytelling platform',
    role: 'Visual Designer & Mini App Designer',
    year: '2024',
    tags: ['Visual Design', 'Mini App Design'],
    url: 'https://farcaster.xyz/miniapps/pmZbrBBIA6wT/emerge',
    color: '#1A1A2E',
    canvasItems: [
      { type: 'hero', x: 200, y: 100, width: 700, image: '/work-emerge.webp' },
      { type: 'heading', x: 200, y: 520, text: 'Emerge' },
      { type: 'text', x: 200, y: 580, width: 500, text: 'Emerge is a creative platform for visual storytelling and mini app experiences. Designed to help creators share their stories in a new way.' },
      { type: 'label', x: 200, y: 680, text: 'Role' },
      { type: 'text', x: 200, y: 710, width: 400, text: 'Visual Designer & Mini App Designer' },
      { type: 'label', x: 200, y: 770, text: 'Year' },
      { type: 'text', x: 200, y: 800, width: 200, text: '2024' },
      { type: 'section', x: 1000, y: 100, text: 'Screenshots' },
      { type: 'placeholder', x: 1000, y: 160, width: 500, height: 350, label: 'App Home' },
      { type: 'placeholder', x: 1000, y: 560, width: 500, height: 350, label: 'Story Creator' },
      { type: 'sticky', x: 1550, y: 160, width: 250, text: 'Built as a Farcaster mini app — designed for the social graph.', color: '#B5E8B5' },
    ],
  },
  crowwd: {
    id: 'crowwd',
    title: 'Crowwd',
    subtitle: 'Crowdfunding and community platform',
    role: 'Product Designer & Visual Designer',
    year: '2024',
    tags: ['Product Design', 'Visual Design'],
    url: null,
    color: '#1A1A2E',
    canvasItems: [
      { type: 'hero', x: 200, y: 100, width: 700, image: '/work-crowwd.webp' },
      { type: 'heading', x: 200, y: 520, text: 'Crowwd' },
      { type: 'text', x: 200, y: 580, width: 500, text: 'Crowwd is a platform for crowdfunding and community-driven project building. Designed the full product experience from onboarding to project management.' },
      { type: 'label', x: 200, y: 680, text: 'Role' },
      { type: 'text', x: 200, y: 710, width: 400, text: 'Product Designer & Visual Designer' },
      { type: 'label', x: 200, y: 770, text: 'Year' },
      { type: 'text', x: 200, y: 800, width: 200, text: '2024' },
      { type: 'section', x: 1000, y: 100, text: 'Screenshots' },
      { type: 'placeholder', x: 1000, y: 160, width: 500, height: 350, label: 'Dashboard' },
      { type: 'placeholder', x: 1000, y: 560, width: 500, height: 350, label: 'Project Page' },
      { type: 'placeholder', x: 1550, y: 160, width: 500, height: 350, label: 'Profile Page' },
      { type: 'sticky', x: 1550, y: 560, width: 250, text: 'Focus on making project creation as simple as writing a tweet.', color: '#A7D8F0' },
    ],
  },
};

// All projects for sidebar navigation
export const ALL_PROJECTS = [
  { id: 'bento', title: 'Bento.fun' },
  { id: 'inner-circle', title: 'Inner Circle' },
  { id: 'velar', title: 'Velar' },
  { id: 'emerge', title: 'Emerge' },
  { id: 'crowwd', title: 'Crowwd' },
];
